- core/Cargo.toml
- core/src/commands.rs
- core/src/logging.rs
- core/src/main.rs
- core/src/oracle_config.rs
- core/src/scans.rs
Close #23
I revamped logging, exit codes aiming to run it as a set-it-and-forget-it service rather than an app. The goal was for logging calls to output to stdout and to the log file (with rotation).
Besides that I simplified `main_loop_iteration`.
TODO:
> Systemd friendly logging

- core/src/commands.rs
- core/src/commands/publish_datapoint.rs
- core/src/main.rs
- core/src/state.rs
> Remove the data point value from PoolCommand::PublishDataPoint(i64)

- bootstrap_config_example.yaml
- core/Cargo.toml
- core/src/bootstrap.rs
- core/src/commands.rs
- core/src/contracts/pool.rs
- core/src/contracts/refresh.rs
- core/src/main.rs
- core/src/node_interface.rs
- core/src/wallet.rs
> Bootstrap command

- core/src/cli_commands.rs
- core/src/cli_commands/bootstrap.rs
- core/src/cli_commands/extract_reward_tokens.rs
- core/src/cli_commands/print_reward_tokens.rs
- core/src/main.rs
- core/src/node_interface.rs
- core/src/wallet.rs
> Remove side-effects from `main`

- core/src/pool_commands/publish_datapoint.rs
> Pass `epoch_count` into `build_publish_datapoint_action` instead of `pool_box_source`

- core/src/datapoint_source.rs
- core/src/datapoint_source/ada_usd.rs
- core/src/datapoint_source/erg_xau.rs
- core/src/oracle_config.rs
> Impl ERG/XAU pair

- core/src/datapoint_source.rs
- core/src/oracle_config.rs
> Add DataSource enum

- core/src/cli_commands/bootstrap.rs
- core/src/contracts/update.rs
> Lock Update NFT in UpdateContract Box

- core/src/cli_commands/bootstrap.rs
- core/src/serde.rs
- core/src/tests/bootstrap_and_run.rs
> Remove `BootstrapConfig::total_oracles` and `total_ballots`

- core/src/address_util.rs
- core/src/main.rs
- core/src/node_interface.rs
- core/src/scans.rs
> Remove node's address conversion

- .github/workflows/release.yml
- core/Cargo.toml
- core/src/api.rs
- core/src/main.rs
- core/src/pool_commands/test_utils.rs
Close #90.
Summary of changes:
- Windows build fixed, by using external build of `openssl` pulled by `vcpkg`.
- Replace REST API implementation using `sincere` with `axum`.
- Add flag to enable REST API, since by default it will expose the server without SSL which is a security concern.
> Fix windows build + port REST API to `axum`

- README.md
- core/Cargo.toml
- core/src/default_parameters.rs
- core/src/main.rs
For verification against EIP-23.
> Impl command to compute base64 contract hashes

- core/Cargo.toml
- core/src/main.rs
> Add missing docs for subcommands + authors

- core/src/oracle_state.rs
> Re-register UTXO-set-scans after UpdatePool command

- core/src/actions.rs
- core/src/api.rs
- core/src/box_kind/oracle_box.rs
- core/src/box_kind/pool_box.rs
- core/src/box_kind/refresh_box.rs
- core/src/box_kind/update_box.rs
- core/src/cli_commands/bootstrap.rs
- core/src/cli_commands/extract_reward_tokens.rs
- core/src/cli_commands/prepare_update.rs
- core/src/cli_commands/transfer_oracle_token.rs
- core/src/cli_commands/update_pool.rs
- core/src/cli_commands/vote_update_pool.rs
- core/src/contracts/oracle.rs
- core/src/main.rs
- core/src/node_interface.rs
- core/src/oracle_state.rs
- core/src/pool_commands.rs
- core/src/pool_commands/publish_datapoint.rs
- core/src/pool_commands/refresh.rs
- core/src/pool_commands/test_utils.rs
- core/src/state.rs
- core/src/wallet.rs
Close #139
Close #141
Close #140
Close #142
Close #145
Close #144
> Distinguish posted and collected oracle boxes, ignore some node errors, fix refresh tx

- core/src/box_kind/ballot_box.rs
- core/src/box_kind/oracle_box.rs
- core/src/box_kind/pool_box.rs
- core/src/box_kind/refresh_box.rs
- core/src/box_kind/update_box.rs
- core/src/cli_commands/bootstrap.rs
- core/src/cli_commands/extract_reward_tokens.rs
- core/src/cli_commands/prepare_update.rs
- core/src/cli_commands/transfer_oracle_token.rs
- core/src/cli_commands/update_pool.rs
- core/src/cli_commands/vote_update_pool.rs
- core/src/contracts/ballot.rs
- core/src/contracts/oracle.rs
- core/src/contracts/pool.rs
- core/src/contracts/refresh.rs
- core/src/contracts/update.rs
- core/src/main.rs
- core/src/oracle_config.rs
- core/src/oracle_state.rs
- core/src/pool_commands/publish_datapoint.rs
- core/src/pool_commands/refresh.rs
- core/src/pool_commands/test_utils.rs
- core/src/scans.rs
- core/src/serde.rs
- core/src/spec_token.rs
Hi, I've added a new SpecToken/TokenIdKind type to replace untyped Tokens.
Most of oracle-core can now benefit from strongly typed tokens, though there are some parts where care is needed (namely bootstrap and post-update).
> Typed tokens

- README.md
- core/src/actions.rs
- core/src/cli_commands/prepare_update.rs
- core/src/cli_commands/update_pool.rs
- core/src/cli_commands/vote_update_pool.rs
- core/src/main.rs
- core/src/serde.rs
- docs/update_epoch_length.md
Close #160
Close #162 
Close #163
Close #165
Close #166
Close #167
Close #168
Close #170
> Fixes during update contract parameters process

- scripts/send_new_oracle.sh
> add send_new_oracle.sh script to send tokens oracle #185;

- core/src/cli_commands/bootstrap.rs
- core/src/oracle_config.rs
- core/src/oracle_state.rs
- core/src/serde.rs
> remove rescan_height and do the wallet rescan from the genesis #189;

- core/src/logging.rs
- core/src/main.rs
- core/src/oracle_state.rs
- core/src/scans.rs
> Add data_dir command line option where scanIDs.json and logs are stored

- core/src/cli_commands/prepare_update.rs
- core/src/node_interface.rs
> fix prepare-update command tx submition failure (missing ballot token minting tx)

- core/src/cli_commands.rs
- core/src/cli_commands/import_pool_update.rs
- core/src/main.rs
- core/src/oracle_config.rs
- core/src/pool_config.rs
> ImportPoolUpdate command to switch to the updated pool config

- README.md
- core/Cargo.toml
- core/src/actions.rs
- core/src/api.rs
- core/src/cli_commands/bootstrap.rs
- core/src/cli_commands/extract_reward_tokens.rs
- core/src/cli_commands/prepare_update.rs
- core/src/cli_commands/transfer_oracle_token.rs
- core/src/cli_commands/update_pool.rs
- core/src/cli_commands/vote_update_pool.rs
- core/src/main.rs
- core/src/node_interface.rs
- core/src/node_interface/node_api.rs
- core/src/oracle_config.rs
- core/src/oracle_state.rs
- core/src/pool_commands/publish_datapoint.rs
- core/src/pool_commands/refresh.rs
- core/src/pool_commands/test_utils.rs
- core/src/scans.rs
- core/src/tests/bootstrap_and_run.rs
- core/src/wallet.rs
- docs/how_to_bootstrap.md
> Add `node_url` instead of `node_ip` and `node_port` in oracle config

- Cargo.toml
- core/Cargo.toml
- core/src/cli_commands.rs
- core/src/cli_commands/bootstrap.rs
- core/src/cli_commands/extract_reward_tokens.rs
- core/src/cli_commands/prepare_update.rs
- core/src/cli_commands/transfer_oracle_token.rs
- core/src/cli_commands/update_pool.rs
- core/src/cli_commands/vote_update_pool.rs
- core/src/explorer_api.rs
- core/src/main.rs
- core/src/node_interface.rs
- core/src/node_interface/node_api.rs
- core/src/oracle_state.rs
- core/src/tests/bootstrap_and_run.rs
- ergo-chain-sim/Cargo.toml
> Wait for tx confirmation in commands + introduce ExplorerApi 

- core/Cargo.toml
- core/src/cli_commands/prepare_update.rs
- core/src/main.rs
- core/src/node_interface/node_api.rs
- core/src/oracle_state.rs
- core/src/wallet.rs
> Handle locked node wallet during the run

- core/src/api.rs
> Expose more pool data at REST API endpoints

- core/src/main.rs
> Fix REST API (tokio runtime premature freeing)

- core/src/main.rs
- core/src/scans/registry.rs
and wait for finish if it is;
Close #261
> Check if node wallet is re-scanning on app launch;

- core/src/api.rs
- core/src/main.rs
- core/src/oracle_state.rs
> Pass OraclePool instance to the REST API request handlers

- core/src/scans/registry.rs
> buyback scan removal if buyback token id is not set in pool config

- core/src/api.rs
- core/src/box_kind/oracle_box.rs
- core/src/cli_commands/prepare_update.rs
- core/src/main.rs
- core/src/oracle_state.rs
- core/src/pool_commands.rs
- core/src/pool_commands/refresh.rs
> Add CollectedDatapointBoxesSource to determine active oracle count in /poolStatus endpoint 

- core/src/api.rs
Close #269 
/oracleHealth - returns OK if our collected datapoint box height is the same as the pool box height OR our posted datapoint box height is greater than the pool box height
> add /oracleHealth endpoint to the API

- core/src/api.rs
> add /poolHealth endpoint for pool status monitoring;
